sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t atomanche/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true atomanche/docker-react npm run test